
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DE_LA_TABLA DONDE EN_ESTO IDENTIFIER LPAREN RPAREN TODO TRAEMEquery : TRAEME TODO DE_LA_TABLA table_name DONDE conditiontable_name : IDENTIFIERcondition : IDENTIFIER EN_ESTO list_valueslist_values : LPAREN IDENTIFIER RPAREN'
    
_lr_action_items = {'TRAEME':([0,],[2,]),'$end':([1,8,11,14,],[0,-1,-3,-4,]),'TODO':([2,],[3,]),'DE_LA_TABLA':([3,],[4,]),'IDENTIFIER':([4,7,12,],[6,9,13,]),'DONDE':([5,6,],[7,-2,]),'EN_ESTO':([9,],[10,]),'LPAREN':([10,],[12,]),'RPAREN':([13,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'table_name':([4,],[5,]),'condition':([7,],[8,]),'list_values':([10,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> TRAEME TODO DE_LA_TABLA table_name DONDE condition','query',6,'p_query_select','parser.py',6),
  ('table_name -> IDENTIFIER','table_name',1,'p_table_name','parser.py',10),
  ('condition -> IDENTIFIER EN_ESTO list_values','condition',3,'p_condition','parser.py',14),
  ('list_values -> LPAREN IDENTIFIER RPAREN','list_values',3,'p_list_values','parser.py',18),
]
